### ISSUE TITLE
Introduction of Blosc as alternative array backend instead of blist

### ISSUE THREAD

**Issue by jjchan121** [rsheftel/raccoon#11]
Currently blist is used as the backend of the array storage.
Could I ask if it is difficult enhance it with option that we can use Blosc array?
https://github.com/Blosc/bcolz

**Comment by jjchan121** [comment]
Yes and that is why I am interested to your project. Also I found the conversion from bcolz's carray back to numpy is quicker than blist while it still enjoys a faster append than numpy, then I think this is a good candidate for raccoon storage.

I would say the bcolz's carray is more similar to numpy array in terms of getting and setting values.
While it has a list like append.

A tutorial notebook is at https://github.com/Blosc/bcolz/blob/master/docs/tutorial_carray.ipynb

**Comment by rsheftel** [comment]
If you are interested in working on this together I would be happy to guide. Otherwise it may be a bit before I get the time to do it myself.

**Comment by rsheftel** [comment]
I have done a major refactoring of the code to now allow any drop-in replacement for the built-in list() function to be used as of v3.0 (to be released this week). When trying with bcolz there are errors because the bcolz.carray does not implement all of the list methods, for example .extend(). If there are other versions of bcolz or extensions to bcolz that cover all the list methods it would now work.

Alternatively if there are modifications to this code that you want to make a PR to work around the bcolz deficiencies (in a nice way, its an excellent package), I would be very happy to look at those.

**Comment by jjchan121** [comment]
Thanks for revisiting this as I have forgotten that I initiated this. Let me take a look and see if there could be a way to do.

**Comment by rsheftel** [comment]
It's been a couple of years, so I will assume this is no longer open.
