### ISSUE TITLE
Custom sort keys / ordering

### ISSUE THREAD

**Issue by tonycpsu** [rsheftel/raccoon#8]
I was wondering if you had any plans to implement custom sorting of rows with the `sort_columns` function.  Things like being able to pass in a custom key or comparator function, sort in reverse, etc.  I don't see any way to do this currently.

**Comment by rsheftel** [comment]
I just committed the change to add the `reverse` argument to `sort_columns()` in https://github.com/rsheftel/raccoon/commit/a49481f0516fe0cf25397ad1c48669a6eaaf5a40

Can you give an example of the custom key or comparator function you would want to be able to use so I can think about how to add that as well.

**Comment by tonycpsu** [comment]
I think the most intuitive way would just to provide the same sort of interface the `sort` and `sorted` methods do, which is a `key` argument that identifies the sort key as a function that's called on each item.

**Comment by rsheftel** [comment]
I added the `key` parameter to the `sort_columns()` function. It now has both `key` and `reverse`. Take a look and let me know if it has the behavior you were thinking, if so I will then upload to PyPi

**Comment by tonycpsu** [comment]
Seems to work as expected.

One thing I don't quite understand is how this fits in with your idea of sorted dataframes.  I gather from the code and comments that a sorted dataframe means "sorted by the index."  That makes sense, but is it possible to have a sorted dataframe that's kept sorted by another column, or is there a reason this feature is limited just to the index?  I ask because generally with the data I'm working with, the index is a surrogate primary key from a database, and therefore not very interesting to sort by.  I find myself using `sort_by_column` instead, but I would make use of the sorted dataframe concept if it were applicable to non-index columns.

**Comment by rsheftel** [comment]
I uploaded the latest version to PyPi so a pip install will get the latest sort_columns()

The idea of the sorted dataframes was mainly for time series data where the index would be the timestamp. This allows for two benefits (1) new timestamps are automatically inserted at the right point and (2) if raccoon knows that the index is in sorted order then lookups are much faster by using the bisect library instead of having to scan through the entire index.

Having a sorted DataFrame where the sort is driven by a column and not an index is not something I thought of, it would probably be a reasonable re-write of the code. Would it be possible for you to just swap the column that is the driver of the sort with the index? Under the covers the index is just another list like the columns and you can even give it a name.

**Comment by tonycpsu** [comment]
Yeah, I understand why you did things the way you did, and honestly it's not that big of a deal to work with things the way they are now.

I can't swap the index and the other columns because the columns in question often contain duplicates, and the index can't have duplicates.  The way you have things set up makes sense for time series data, and for the sizes of dataframes I'm working with, and the occasional sort call isn't that big of a deal.
